package com.onlinebanking.helpers;

public class HTML {
  public static String htmlEmailTemplate(String token,int code) {
    String url="http://127.0.0.1:8070/verify?token="+token+"&code="+code;
    
    String emailTemplate="<!DOCTYPE html>\n"
    		+ "<html lang=\"en\">\n"
    		+ "<head>\n"
    		+ "  <meta charset=\"UTF-8\">\n"
    		+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
    		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    		+ "  <style>\n"
    		+ "    *{\n"
    		+ "      box-sizing: border-box;\n"
    		+ "      font-family: Comfortaa;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    body{\n"
    		+ "      height: 100vh;\n"
    		+ "      background-color: rgb(212,222,230);\n"
    		+ "      display: flex;\n"
    		+ "      align-items: center;\n"
    		+ "      justify-content: center;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .wrapper{\n"
    		+ "      width: 550px;\n"
    		+ "      height: auto;\n"
    		+ "      padding:15px;\n"
    		+ "      background: white;\n"
    		+ "      border-radius: 7px;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .email-msg-header{\n"
    		+ "      text-align: center;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .company-name{\n"
    		+ "      width:100%;\n"
    		+ "      font-size: 35px;\n"
    		+ "      color: gray;\n"
    		+ "      text-align: center;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .welcome-text{\n"
    		+ "      text-align: center;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .verify-account-btn-wrapper{\n"
    		+ "      text-align: center;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .verify-account-btn{\n"
    		+ "      padding: 15px;\n"
    		+ "      color: white;\n"
    		+ "      background-color: rgb(0,109,252);\n"
    		+ "      text-decoration: none;\n"
    		+ "      border-radius: 5px;\n"
    		+ "    }\n"
    		+ "\n"
    		+ "    .copy-right{ \n"
    		+ "      padding: 15px;\n"
    		+ "      color:gray;\n"
    		+ "      font-size:14px;\n"
    		+ "      margin: 20px 0px 0px 0px;\n"
    		+ "      text-align: center;\n"
    		+ "    }\n"
    		+ "  </style>\n"
    		+ "  <title>Email</title>\n"
    		+ "</head>\n"
    		+ "<body>\n"
    		+ "  \n"
    		+ "  <!-- Wrapper -->\n"
    		+ "  <div class=\"wrapper\">\n"
    		+ "\n"
    		+ "    <!-- Email MSG Header -->\n"
    		+ "    <h2 class=\"email-msg-header\">\n"
    		+ "      Welcome and Thank You Choosing \n"
    		+ "    </h2>\n"
    		+ "    <!-- Email MSG Header -->\n"
    		+ "\n"
    		+ "    <!-- Company Name -->\n"
    		+ "    <div class=\"company-name\">\n"
    		+ "      Easy Way Bank\n"
    		+ "    </div>\n"
    		+ "    <!-- Company Name -->\n"
    		+ "    <hr>\n"
    		+ "    <!-- Welcome Text -->\n"
    		+ "    <p class=\"welcome-text\">\n"
    		+ "      Your account has been successfully registered,"
                    + " please click below to verify your account \n"
    		+ "    </p>\n"
    		+ "    <!-- Welcome Text -->\n"
    		+ "    <br>\n"
    		+ "    <br>\n"
    		+ "    <!-- Verify Account Button -->\n"
    		+ "    <div class=\"verify-account-btn-wrapper\">\n"
    		+ "      <a href=\""+url+"\" class=\"verify-account-btn\">Verify Account</a>\n"
    		+ "    </div>\n"
    		+ "    <!-- Verify Account Button -->\n"
    		+ "\n"
    		+ "    <!-- Copy Right Wrapper -->\n"
    		+ "    <div class=\"copy-right\">\n"
    		+ "      &copy;Copy Right 2022.All Rights Reserved\n"
    		+ "    </div>\n"
    		+ "    <!-- Copy Right Wrapper -->\n"
    		+ "\n"
    		+ "  </div>\n"
    		+ "  <!-- Wrapper -->\n"
    		+ "    \n"
    		+ "</body>\n"
    		+ "</html>\n";
    
    return emailTemplate;    
  }
}
